### PR TITLE
Worker safe shutdown

### LINKED ISSUE #127: Graceful worker shutdown

### PR DESCRIPTION
**Pull request by ammen99**
Fixes #127 

~~I tried to test server+worker locally, but I encountered #142, which makes it impossible for a worker to register itself again after being registered in the database more than once ...~~ Now that bug is fixed, but another one has come around ..

### CODE REVIEW

**Comment by ammen99** [comment]
I think shut down == retire, so we are waiting for the jobs to get finished, right?

**Comment by JohannesGaessler** [comment]
It would maybe be nice to have a --force option that just cancels all jobs but I don't think it's a priority.

**Comment by ammen99** [comment]
> It would maybe be nice to have a --force option that just cancels all jobs but I don't think it's a priority.

I also don't think it is very important since we still have crashes to fix like #145, plus I don't think we have tested the scheduler/dispatcher at all so far ...

**Comment by ammen99** [comment]
@JohannesGaessler Should I take your comment as an approving review?

**Comment by ammen99** [comment]
> I didn't approve because there was talk in the OP about a bug but I assume it's fixed then?

Oh, I should have clarified. The bug is when testing the worker, not directly related or caused by this PR.

**Pull request merged**
